services:
  wordpress_db:
    image: mariadb:10.11
    container_name: wp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PHP_QuadCore_root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_usuario
      MYSQL_PASSWORD: PHP_QuadCore_wp
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wp_site
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wp_usuario
      WORDPRESS_DB_PASSWORD: PHP_QuadCore_wp
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - .:/var/www/html

volumes:
  db_data:
  wp_data: